### ISSUE TITLE
path field not working on "create endpoint page""

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#237] opened 2016-11-15 23:48 UTC

**Comment by tbookless** [comment] 2016-11-22 18:43
@sbuxjava into which field are you entering www.google.com?

**Comment by tbookless** [comment] 2016-11-30 21:26
I believe that this is a duplicate of #298 

The See Also links require full URL's - https://www.google.com

**Closed by tbookless** 2016-11-30 21:26 UTC
