### ISSUE TITLE
REG-387 Loading the homepage gives bad error request

### ISSUE THREAD

**Issue by sbuxjava** [tomitribe/tribestream-api-registry#244] opened 2016-11-16 23:05 UTC
go to https://starbucks.tomitribe.com/registry/
we get "bad request " popup on chrome

**Comment by tbookless** [comment] 2016-11-22 19:09
I believe that this is probably caused by an expired authorization token. We should be sending you back to the login page.

**Comment by tbookless** [comment] 2016-11-27 17:48
fixed in 0.5.4

**Comment by tbookless** [comment] 2016-11-30 18:35
This is a new issue that has to do with the Elastic Search Index being empty on a brand new install. We have another Jira open to address this.

**Comment by tbookless** [comment] 2016-12-02 00:19
fixed in 0.5.8

**Closed by tbookless** 2016-12-02 00:19 UTC
Labels: bug
